# This is a basic workflow to help you get started with Actions

name: autoSetGithubPages

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: master
      - name: Cache
        uses: pnpm/action-setup@v2
        with: 
          version: 7.9.5
      # Runs a set of commands using the runners shell
      - name: UseNode
        uses: actions/setup-node@v3 
        with: 
          node-version: 16.17.0
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: github-pages
          full_commit_message: ${{ github.event.head_commit.message }}
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{secrets.APPLICATION_ID}}
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
  
# name: algolia
# on:
#   push:
#     branches: ["github-pages"]
# jobs:
#   algolia:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Get the content of algolia.json as config
#         id: algolia_config
#         run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
#       - name: Push indices to Algolia
#         uses: signcl/docsearch-scraper-action@master
#         env:
#           APPLICATION_ID: ${{secrets.APPLICATION_ID}}
#           API_KEY: ${{ secrets.API_KEY }}
#           CONFIG: ${{ steps.algolia_config.outputs.config }}